---
- hosts: docker
  remote_user: ubuntu
  tasks:
  - name: "Configure app server(s)"
    docker:
      name: nginx in docker
      image: englert/nginx
      state: present
      ports:
      - "80:80"